name: stock_sync
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.3
  flutter_riverpod: ^3.0.3
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.2
  flutter_secure_storage: ^9.2.4
  share_plus: ^12.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  firebase_storage: ^13.0.3
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
