// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tFAwVyBX6ewmzJ_YHZfmLtawHHYzqWE',
    appId: '1:140635634339:web:f24335f63a1dd39d379d16',
    messagingSenderId: '140635634339',
    projectId: 'stocksync-176d1',
    authDomain: 'stocksync-176d1.firebaseapp.com',
    storageBucket: 'stocksync-176d1.firebasestorage.app',
    measurementId: 'G-MC7SDPSV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHhaeCVJpSCSq-RdKL_aiOOfJ5jxSh2A',
    appId: '1:140635634339:android:efef449d0700317e379d16',
    messagingSenderId: '140635634339',
    projectId: 'stocksync-176d1',
    storageBucket: 'stocksync-176d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRol1sfeV67ydJeHYB8r9CI1aprSyWRDA',
    appId: '1:140635634339:ios:e874f42e0ed4c6a1379d16',
    messagingSenderId: '140635634339',
    projectId: 'stocksync-176d1',
    storageBucket: 'stocksync-176d1.firebasestorage.app',
    iosBundleId: 'com.hxlabs.stocksync',
  );
}
